/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#006875",
        "surface-container-lowest": "#000000",
        "tertiary-container": "#fe00fe",
        "on-background": "#ffffff",
        "inverse-primary": "#6d23f9",
        "on-tertiary-fixed": "#320032",
        "secondary-dim": "#00d4ec",
        "error": "#ff6e84",
        "surface": "#0e0e0e",
        "tertiary-dim": "#ff51fa",
        "primary-container": "#ac8eff",
        "inverse-on-surface": "#565555",
        "primary": "#b89fff",
        "on-secondary-fixed-variant": "#005964",
        "background": "#0e0e0e",
        "on-tertiary": "#400040",
        "tertiary-fixed-dim": "#ff61f8",
        "surface-tint": "#b89fff",
        "on-surface-variant": "#adaaaa",
        "primary-fixed-dim": "#a07dff",
        "on-error": "#490013",
        "on-secondary-container": "#e8fbff",
        "on-error-container": "#ffb2b9",
        "surface-variant": "#262626",
        "tertiary": "#ff51fa",
        "surface-bright": "#2c2c2c",
        "on-secondary-fixed": "#003a42",
        "surface-dim": "#0e0e0e",
        "surface-container": "#1a1a1a",
        "error-dim": "#d73357",
        "outline": "#767575",
        "error-container": "#a70138",
        "surface-container-highest": "#262626",
        "on-primary-fixed-variant": "#350088",
        "surface-container-high": "#20201f",
        "on-tertiary-fixed-variant": "#6a006a",
        "on-primary": "#37008e",
        "outline-variant": "#484847",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#ff81f5",
        "secondary": "#00e3fd",
        "on-surface": "#ffffff",
        "primary-dim": "#834fff",
        "on-primary-container": "#2a0070",
        "surface-container-low": "#131313",
        "secondary-fixed": "#26e6ff",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary": "#004d57",
        "on-tertiary-container": "#230023",
        "inverse-surface": "#fcf9f8",
        "primary-fixed": "#ac8eff",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
